import React from 'react';
import {
  Landmark,
  Train,
  TreePine,
  Factory,
  Warehouse,
  Gavel,
  Banknote,
  Building,
  HelpCircle,
  Home,
  Coins,
  Ticket,
  Loader2,
  Hotel,
  Dices,
  Map,
  Hammer,
  Trash2,
  Swords,
  Shield,
  Heart,
  Droplets,
  Flame,
  Zap,
  Briefcase,
  PlusCircle,
  MinusCircle,
  ArrowRightLeft,
  BookOpen,
  Users,
  Settings,
  LogOut,
  ChevronLeft,
  ChevronRight,
  MoreHorizontal,
  X,
  Eye,
  Car,
  Gem,
  Handshake,
  Store,
  User,
  Wallet,
  Wrench,
  CircleDollarSign,
  Spy,
  Scroll,
  FileText
} from 'lucide-react';

const iconMap = {
  Landmark,
  Metro: Train,
  Train,
  Forêt: TreePine,
  Usine: Factory,
  Entrepôt: Warehouse,
  Commissariat: Gavel,
  Banque: Landmark,
  Building,
  'Non défini': HelpCircle,
  Home,
  Coins,
  Ticket,
  Loader2,
  Hôtel: Hotel,
  Casino: Dices,
  Map,
  Hammer,
  Trash2,
  Swords,
  Shield,
  Heart,
  Droplets,
  Flame,
  Zap,
  Briefcase,
  PlusCircle,
  MinusCircle,
  ArrowRightLeft,
  BookOpen,
  Users,
  Settings,
  LogOut,
  ChevronLeft,
  ChevronRight,
  MoreHorizontal,
  X,
  Eye,
  Car,
  Gem,
  Handshake,
  Store,
  User,
  Wallet,
  Wrench,
  CircleDollarSign,
  Spy,
  Scouts: Users,
  Bounty: CircleDollarSign,
  'Ticket de métro': Ticket,
  'Rapport de reconnaissance': FileText,
  Blueprint: Scroll,
  default: Landmark,
};

export type IconName = keyof typeof iconMap;

const Icon: React.FC<React.SVGProps<SVGSVGElement> & { name: IconName | string }> = ({ name, ...props }) => {
  const LucideIcon = iconMap[name as IconName] || iconMap.default;
  return <LucideIcon {...props} />;
};

export default Icon;