// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://odnnuqgkkzhmkxfafzhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kbm51cWdra3pobWt4ZmFmemhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMzA3NDMsImV4cCI6MjA2NjcwNjc0M30.OuDofuERpko4EuLyrnsAFr9m0g611PgRvQfD2McM790";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);